export const categories = [
  {
    id: 1,
    name: "الرخام",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 2,
    name: "البورسلان",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 3,
    name: "السيراميك",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 4,
    name: "الباركيه",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 5,
    name: "النوافذ",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 6,
    name: "الديكورات",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 7,
    name: "الأبواب",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 8,
    name: "الصفائح الحجرية",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 9,
    name: "الجبس",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 10,
    name: "الحجر",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 11,
    name: "الدهانات",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 12,
    name: "العوازل",
    subCategories: null,
    criteriaItems: null,
  },
  // {
  //   id: 13,
  //   name: "البوابات الإلكترونية",
  //   subCategories: null,
  //   criteriaItems: null,
  // },
  {
    id: 14,
    name: "مفاتيح وأفياش",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 15,
    name: "مواد صحية وخزانات",
    subCategories: null,
    criteriaItems: null,
  },
  {
    id: 16,
    name: "التكييف",
    subCategories: null,
    criteriaItems: null,
  },
  // {
  //   id: 17,
  //   name: "الإنارة",
  //   subCategories: null,
  //   criteriaItems: null,
  // },
];
