export const subCategories = [
  {
    id: 1,
    name: "رخام الأرضيات الداخلية والخارجية",
    categoryId: 1,
    products: [],
  },
  {
    id: 2,
    name: "رخام المطابخ والحمامات",
    categoryId: 1,
    products: [],
  },
  {
    id: 3,
    name: "رخام الجدران",
    categoryId: 1,
    products: [],
  },
  {
    id: 4,
    name: "رخام الواجهات",
    categoryId: 1,
    products: [],
  },
  {
    id: 5,
    name: "بديل الرخام",
    categoryId: 1,
    products: [],
  },
  {
    id: 6,
    name: "بورسلان الأرضيات الداخلية",
    categoryId: 2,
    products: [],
  },
  {
    id: 7,
    name: "بورسلان الحمامات والمطابخ",
    categoryId: 2,
    products: [],
  },
  {
    id: 8,
    name: "بورسلان الواجهات",
    categoryId: 2,
    products: [],
  },
  {
    id: 9,
    name: "بورسلان الأرضيات الخارجية",
    categoryId: 2,
    products: [],
  },
  {
    id: 10,
    name: "سيراميك الأرضيات الداخلية",
    categoryId: 3,
    products: [],
  },
  {
    id: 11,
    name: "سيراميك الجدران",
    categoryId: 3,
    products: [],
  },
  {
    id: 12,
    name: "سيراميك الحمامات والمطابخ",
    categoryId: 3,
    products: [],
  },
  {
    id: 13,
    name: "سيراميك الأرضيات الخارجية",
    categoryId: 3,
    products: [],
  },
  {
    id: 14,
    name: "باركيه الأرضيات الداخلية",
    categoryId: 4,
    products: [],
  },
  {
    id: 15,
    name: "باركيه مقاوم للرطوبة",
    categoryId: 4,
    products: [],
  },
  {
    id: 16,
    name: "باركيه للأماكن التجارية",
    categoryId: 4,
    products: [],
  },
  {
    id: 17,
    name: "نوافذ سحاب",
    categoryId: 5,
    products: [],
  },
  {
    id: 18,
    name: "نوافذ مفصلية",
    categoryId: 5,
    products: [],
  },
  {
    id: 19,
    name: "نوافذ قلاب",
    categoryId: 5,
    products: [],
  },
  {
    id: 20,
    name: "الشتر",
    categoryId: 5,
    products: [],
  },
  {
    id: 21,
    name: "القفاري",
    categoryId: 6,
    products: [],
  },
  {
    id: 22,
    name: "الأبواب الداخلية",
    categoryId: 7,
    products: [],
  },
  {
    id: 23,
    name: "الأبواب الخارجية",
    categoryId: 7,
    products: [],
  },
  {
    id: 24,
    name: "أبواب الحمامات والمطابخ",
    categoryId: 7,
    products: [],
  },
  {
    id: 25,
    name: "الصفائح الخشبية",
    categoryId: 8,
    products: [],
  },
  {
    id: 26,
    name: "الصفائح الرخامية",
    categoryId: 8,
    products: [],
  },
  {
    id: 27,
    name: "الصفائح الطينية",
    categoryId: 8,
    products: [],
  },
  {
    id: 28,
    name: "الصفائح الحجرية الطبيعية",
    categoryId: 8,
    products: [],
  },
  {
    id: 29,
    name: "جبس مقاوم للرطوبة",
    categoryId: 9,
    products: [],
  },
  {
    id: 30,
    name: "جبس للأسقف",
    categoryId: 9,
    products: [],
  },
  {
    id: 31,
    name: "حجر للأرضيات",
    categoryId: 10,
    products: [],
  },
  {
    id: 32,
    name: "حجر للجدران",
    categoryId: 10,
    products: [],
  },
  {
    id: 33,
    name: "حجر للواجهات الخارجية",
    categoryId: 10,
    products: [],
  },
  {
    id: 34,
    name: "دهانات الجدران الداخلية",
    categoryId: 11,
    products: [],
  },
  {
    id: 35,
    name: "دهانات الجدران الخارجية",
    categoryId: 11,
    products: [],
  },
  {
    id: 36,
    name: "الأساسات والمعاجين والمخففات",
    categoryId: 11,
    products: [],
  },
  {
    id: 37,
    name: "دهانات الأرضيات",
    categoryId: 11,
    products: [],
  },
  {
    id: 38,
    name: "عوازل حرارية",
    categoryId: 12,
    products: [],
  },
  {
    id: 39,
    name: "عوازل صوتية",
    categoryId: 12,
    products: [],
  },
  {
    id: 40,
    name: "عوازل مائية",
    categoryId: 12,
    products: [],
  },
  {
    id: 41,
    name: "بوابات فتح أمامي",
    categoryId: 13,
    products: [],
  },
  {
    id: 42,
    name: "بوابات متأرجحة",
    categoryId: 13,
    products: [],
  },
  {
    id: 43,
    name: "بوابات رفع عمودي",
    categoryId: 13,
    products: [],
  },
  {
    id: 44,
    name: "مكيفات سبليت",
    categoryId: 14,
    products: [],
  },
  {
    id: 45,
    name: "مكيفات النافذة",
    categoryId: 14,
    products: [],
  },
  {
    id: 46,
    name: "مكيفات مركزية",
    categoryId: 14,
    products: [],
  },
  {
    id: 47,
    name: "مكيفات الكاسيت",
    categoryId: 14,
    products: [],
  },
  {
    id: 48,
    name: "مفتاح تسكيره",
    categoryId: 15,
    products: [],
  },
  {
    id: 49,
    name: "مفتاح أحادي",
    categoryId: 15,
    products: [],
  },
  {
    id: 50,
    name: "مفتاح ثنائي",
    categoryId: 15,
    products: [],
  },
  {
    id: 51,
    name: "مفتاح ثلاثي",
    categoryId: 15,
    products: [],
  },
  {
    id: 52,
    name: "مفتاح رباعي",
    categoryId: 15,
    products: [],
  },
  {
    id: 53,
    name: "مفتاح مكيف",
    categoryId: 15,
    products: [],
  },
  {
    id: 54,
    name: "مفتاح سخان",
    categoryId: 15,
    products: [],
  },
  {
    id: 55,
    name: "مفتاح ستارة",
    categoryId: 15,
    products: [],
  },
  {
    id: 56,
    name: "مفتاح دايمر",
    categoryId: 15,
    products: [],
  },
  {
    id: 57,
    name: "مفتاح جرس",
    categoryId: 15,
    products: [],
  },
  {
    id: 58,
    name: "فيش ثلاثي",
    categoryId: 15,
    products: [],
  },
  {
    id: 59,
    name: "USB, USBc فيش",
    categoryId: 15,
    products: [],
  },
  {
    id: 60,
    name: "مجرى أفياش",
    categoryId: 15,
    products: [],
  },
  {
    id: 61,
    name: "أفياش للمجرى",
    categoryId: 15,
    products: [],
  },
  {
    id: 62,
    name: "فيش تليفون",
    categoryId: 15,
    products: [],
  },
  {
    id: 63,
    name: "فيش دش",
    categoryId: 15,
    products: [],
  },
  {
    id: 64,
    name: "فيش إيثرنت",
    categoryId: 15,
    products: [],
  },
  {
    id: 65,
    name: "الخلاطات",
    categoryId: 16,
    products: [],
  },
  {
    id: 66,
    name: "كراسي الحمامات والسيفونات",
    categoryId: 16,
    products: [],
  },
  {
    id: 67,
    name: "السخانات",
    categoryId: 16,
    products: [],
  },
  {
    id: 68,
    name: "أحواض الاستحمام",
    categoryId: 16,
    products: [],
  },
  {
    id: 69,
    name: "أنظمة الدش",
    categoryId: 16,
    products: [],
  },
  {
    id: 70,
    name: "مخارج مياه للدش",
    categoryId: 16,
    products: [],
  },
  {
    id: 71,
    name: "الشطافات",
    categoryId: 16,
    products: [],
  },
  {
    id: 72,
    name: "لوازم السباكة",
    categoryId: 16,
    products: [],
  },
  {
    id: 73,
    name: "صفايات",
    categoryId: 16,
    products: [],
  },
  {
    id: 74,
    name: "مغاسل الحمام",
    categoryId: 16,
    products: [],
  },
  {
    id: 75,
    name: "خزانات المياه",
    categoryId: 16,
    products: [],
  },
  {
    id: 76,
    name: "ملحقات الحمام",
    categoryId: 16,
    products: [],
  },
];
